docs : Update README
boostcampaitech3/final-project-level3-cv-01 pull request #94
Opened 2022-06-13 14:28 UTC by Somang-Kang

## 작업내용
작업한 내용

## 리뷰요청 내용
readme 수정

## Description
- 팀원소개 추가
- 데이터셋 링크 연결
- 모델파이프라인, 실험과정 이미지 변경
- 디렉토리 오타 수정
- 해충 detection 실험 결과 추가

closed :

ref :
#93

2022-06-13 14:30 UTC, kkt4828 requested changes
위에랑 맞춰주세요 ㅠ

2022-06-13 14:30 UTC, kkt4828 commented on README.md
> +│   │    	    └── Navigator.jsx
여기 공백 맞춰주세요!!

2022-06-13 14:39 UTC, Somang-Kang commented on README.md
> +│   │    	    └── Navigator.jsx
수정했습니다!

2022-06-13 14:40 UTC, kkt4828 requested changes

2022-06-13 14:40 UTC, kkt4828 commented on README.md
> +│   │       └── Navigator.jsx
Login.jsx 랑 맞춰야할거 같아요!

2022-06-13 14:43 UTC, kkt4828 commented on README.md
> +│   │       └── Navigator.jsx
아 넵넵

2022-06-13 14:43 UTC, kkt4828 approved these changes

2022-06-13 14:43 UTC, kkt4828 approved these changes

2022-06-13 14:44 UTC, kkt4828 approved these changes

2022-06-13 17:13 UTC, parkgr95 approved these changes
고생하셨습니다!

2022-06-14 04:47 UTC, variety82 approved these changes
팀 소개 첫부분에 사진 추가해도 좋을 것 같습니다, 나머지는 다 확인했습니다
고생하셨어요!

2022-06-14 04:47 UTC, variety82 commented on README.md
사진 추가해도 괜찮을 것 같아요!

2022-06-14 05:58 UTC, mata1139 commented
PR 요청 늦게 확인해서 죄송합니다. 
```.DS_Store``` 파일이 두 개 포함되어있는데 삭제해야 할 것 같습니다.

2022-06-14 09:36 UTC, Somang-Kang commented
모두 수정했습니다. 확인부탁드려요!

2022-06-14 09:39 UTC, merged